config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :contacts, path: ''do
		collection do
			post :import
      get 'remove_all'
		end
	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'home/index'
  root 'contacts#index'
  get "contacts/:id", to: redirect("/%{id}")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
	def self.import(file)
    counter = 0
		CSV.foreach(file.path, headers: true, header_converters: :symbol) do |row|
			contact = Contact.assign_from_row(row)
      if contact.save
        counter += 1
      else
        puts "#{contact.name} - #{contact.errors.full_messages.jion(",")}"
      end
		end
    counter
	end

	extend FriendlyId

  friendly_id :name, use: [:slugged, :history, :finders]

  def should_generate_new_friendly_id?
    name_changed?
  end

	def self.assign_from_row(row)
    contact = Contact.where(name: row[:name]).first_or_initialize
    contact.assign_attributes row.to_hash
    contact
  end
	# def self.open_spreadsheet(file)
	# 	case File.extname(file.original_filename)
	# 		when ".csv" then Roo::CSV.new(file.path, nil, :ignore)
	# 		when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
	# 		when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
	# 		else raise "Unknown file type: #{file.original_filename}"
	# 	end
	# end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
		respond_to do |format|
			format.html
			format.csv { send_data @contacts.to_csv }
		end
  end

  def remove_all
    Contact.delete_all
    flash[:notice] = "You have removed all contacts!"
    redirect_to contacts_path
  end

	def import
		count = Contact.import params[:file]
		redirect_to contacts_path, notice: "Contacts #{count} imported."
	end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :phone)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the current layout name. Allows asserting the rendered layout name
  # in our feature specs as an alternative to the deprecated #render_template

  # Select the appropriate Boostrap class for Rails's flash messages
  def bootstrap_class_for(flash_type)
    case flash_type
    when 'success'
      'alert-success'   # Green
    when 'error'
      'alert-danger'    # Red
    when 'alert'
      'alert-warning'   # Yellow
    else
      'alert-info'      # Blue
    end
  end

  # Display model validation errors in form templates
  def display_validation_errors(object)
    return '' if object.errors.empty?

    header = I18n.t('activerecord.errors.template.header',
                    count: object.errors.count)
    msgs = object.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

    html = <<-HTML
      <div class="alert alert-danger alert-dismissable" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
        </button>
        <h4>
          #{header}
        </h4>
        <ul>#{msgs}</ul>
      </div>
    HTML

    html.html_safe
  end
end

app/views/contacts/_form.html.haml
= simple_form_for(@contact) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit

app/views/contacts/edit.html.haml
%h1 Editing contact

= render 'form'

= link_to 'Show', @contact
\|
= link_to 'Back', contacts_path

app/views/contacts/index.html.haml
%h1 Listing contacts

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @contacts.each do |contact|
      %tr
        %td= contact.name
        %td= link_to 'Show', contact
        %td= link_to 'Edit', edit_contact_path(contact)
        %td= link_to 'Destroy', contact, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

  = form_tag import_contacts_path, multipart: true do
    .text-center
      = file_field_tag :file
    = submit_tag "Import", class: "btn btn-primary"

app/views/contacts/new.html.haml
%h1 New contact

= render 'form'

= link_to 'Back', contacts_path

app/views/contacts/show.html.erb
<body class="home page-template-default page page-id-4 page-child parent-pageid-11 layout-full boxed pagination-load-more no-page-header cbox-share-twitter cbox-share-facebook cbox-share-googleplus cbox-share-pinterest no-header-slider no-header-sidebars responsive-layout no-breadcrumbs no-slider-button-thumbnails no-page-bottom-padding">
  <span id="top"></span>
  <div id="page" class="main-container">
    <div class="fixed-header-box">
      <header class="main-header">
        <div class="first-row">
          <a href="" id="mp-menu-trigger" class="icon-b" data-icon="&#57801;">Open/Close Menu</a>
          <div class="logo-wrapper">
            <a href="" title="Seyha &amp; Linna" class="logo">
              <%= image_tag "logo2.png", class: "show-hidpi-inline", size: "210x112", alt: "Seyha &amp; LInna" %>
            </a>
            <div class="clearboth"></div>
            <a href="" title="Nick &amp; Sarah" class="combined-logo-title">
              <div class="site-title-part left-name">Seyha</div>
              <div class="site-title-part name-delimiter">&amp;</div>
              <div class="site-title-part right-name">Linna</div>
            </a>
            <span class="logo-tagline">ARE GETTING MARRIED!</span>
          </div>
        </div>
        <div class="second-row">
          <div class="limit-wrapper">
            <div class="second-row-columns">
              <div class="header-center">
              </div>
            </div>
          </div>
        </div>
      </header>
        <%= image_tag 'svg/menu-lines.svg', class: 'menu-lines'%>
    </div>
    <div class="shadow-bottom"></div>
    <div class="boxed-layout">
      <div class="page-dash-wrapper">
        <div class="pane-wrapper clearfix">
          <header id="header-middle" class="row normal type-featured" style="background-color:#ffffff;min-height:0px">
            <div class="limit-wrapper">
              <div class="header-middle-content">
              </div>
            </div>
          </header>
          <div id="main-content">

            <div id="main" role="main" class="layout-full">
              <div class="limit-wrapper">
                <div class="pane main-pane">
                  <div class="row">
                    <div class="page-outer-wrapper">
                      <div class="clearfix page-wrapper">
                        <article id="post-4" class="full post-4 page type-page status-publish hentry">
                          <div class="page-content no-image">
                            <div class="push" style='height:20px'></div>
                            <h1 style="text-align: center;">Wedding Invitation</h1>
                            <div class="push" style='height:20px'></div>
                            <%= image_tag 'element-5.svg', class: 'aligncenter', style: 'position: relative; z-index: 99; bottom: -18px; left: -10px;'%>
                            <div class="push" style='margin-bottom:-10px'></div>
                            <div class="row ">
                              <div class="wpv-grid grid-1-5  wpv-first-level first unextended" style="padding-top:0px;padding-bottom:0px" id="wpv-column-a2206aded3ddee2c12400a3059dbbba8">
                                <div class="push" style='height:80px'></div>
                                  <%= image_tag "portrait-man1.svg", class: "aligncenter size-full wp-image-6724", size: "165" %>
                                </p>
                                <h3 style="text-align: center;">Heng Seyha</h3>
                              </div>
                              <div class="wpv-grid grid-3-5  wpv-first-level unextended" style="padding-top:0px;padding-bottom:0px" >

                                <div id="layerslider_1" class="ls-wp-container fitvidsignore" style="margin:0 auto;margin-bottom: 0px;">
                                  <div class="ls-slide1" data-ls="duration:4000;transition2d:5;kenburnsscale:1.2;">
                                    <%= image_tag "profile1.png", class: "ls-l", style: "border-radius: 1000px;top:0px;left:20px;", size: '800' %>
                                  </div>
                                </div>
                                <div class="push" style='height:3px'></div>
                              </div>
                              <div class="wpv-grid grid-1-5  wpv-first-level unextended" style="padding-top:0px;padding-bottom:0px" id="wpv-column-74d59e477a3b247776912d3411fd10bc">
                                <div class="push" style='height:80px'></div>
                                <%= image_tag "portrait-woman1.svg", class: "aligncenter size-full wp-image-6724", size: "165" %>
                                </p>
                                <h3 style="text-align: center;">Chhoeun Linna</h3>
                              </div>
                            </div>
                            <div class="row ">
                              <h1 style="text-align: center;">SATURDAY &#8211; 23 DECEMBER 2017<br>AT 4:00 O'CLOCK AT THE EVENING</h1>
                              <center>
                                <h3 style="position: relative;top: 95px;font-size: 3.3em;color: #F07677;font-family: 'Angkor', 'Passion One';text-transform:uppercase;"><%= @contact.name %></h3>
                                <%= image_tag 'line.png', size: '550x250', style: 'margin-top:60px;' %>
                              </center>
                              <center><p style="font-size: 1.6em;">វេលាម៉ោង 4:00 រសៀលនៅគេហដ្ឋានខាងស្រី ភូមិក្បាលស្ពាន ឃុំម៉ាឡៃ ស្រុកម៉ាឡៃ ខេត្តបន្ទាយមានជ័យ</p></center>
                              <div class="wpv-grid grid-1-3  wpv-first-level first unextended" style="padding-top:0px;padding-bottom:0px"
                                id="wpv-column-b3c1d760f051b4c511323e89f6a6a50f">
                                <div class="push" style='height:10px'></div>
                              </div>
                            </div>
                            <div class="row ">
                              <div class="wpv-grid grid-1-1  wpv-first-level first unextended animation-fade-in animated-active"
                                style="padding-top:0px;padding-bottom:0px" id="wpv-column-30e760b17da7fc5967777b7b33b54e4e">
                                <div class="sep-3"></div>
                                <div class="push" style='height:5px'></div>
                                <h3 style="text-align: center;">Thank you for joining our special day with us</h3>
                                <h5 style="text-align: center;">~ we are sorry if something wrong in the party ~</h5>
                                <div class="push" style='height:40px'></div>
                              </div>
                            </div>
                            <div class="row ">
                              <div class="wpv-grid grid-1-1 wpv-first-level first has-background extended animation-fade-in animated-active"
                                style="
                                    background:  url(<%= asset_path 'bor.png' %>) repeat-y center bottom;
                                    background-size: auto;
                                    background-attachment: scroll;
                                  background-color:#688a72;padding-top:15px;padding-bottom:35px" id="wpv-column-2573d5b8871ad2f811cd9ceeda5e6d62">
                                <div class="extended-column-inner">
                                  <div class="sep-text single centered">
                                    <span class="sep-text-before">
                                      <div class="sep-text-line"></div>
                                    </span>
                                    <div class="content">
                                      <h2>Just</h2>
                                    </div>
                                    <span class="sep-text-after">
                                      <div class="sep-text-line"></div>
                                    </span>
                                  </div>
                                  <div class="push" style='height:50px'></div>
                                    <center><div class="demo1 dsCountDown ds-white"></div></center>
                                  <div class="push" style='height:50px'></div>
                                  <h2 style="text-align: center;"> until we get parties!</h2>
                                </div>
                              </div>
                            </div>
                          </div>
                        </article>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <iframe src="https://www.google.com/maps/embed?pb=!1m26!1m12!1m3!1d24500.4754645717!2d102.36376795537082!3d13.569513916099073!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!4m11!3e6!4m3!3m2!1d12.8914285!2d102.97319189999999!4m5!1s0x311b4190c42cef61%3A0x1eaead461cb31924!2sUnnamed+Road%2C+Malai!3m2!1d13.571629199999999!2d102.36251!5e0!3m2!1sen!2skh!4v1513180698357" width="100%" height="650px" frameborder="0" style="border:0" allowfullscreen></iframe>
          <div class="copyrights">
            <div class="limit-wrapper">
              <div class="row">
                <div class="push" style='height:20px'></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/home/index.html.erb
<body class="home page-template-default page page-id-4 page-child parent-pageid-11 layout-full boxed pagination-load-more no-page-header cbox-share-twitter cbox-share-facebook cbox-share-googleplus cbox-share-pinterest no-header-slider no-header-sidebars responsive-layout no-breadcrumbs no-slider-button-thumbnails no-page-bottom-padding">
  <span id="top"></span>
  <div id="page" class="main-container">
    <div class="fixed-header-box">
      <header class="main-header">
        <div class="first-row">
          <a href="#" id="mp-menu-trigger" class="icon-b" data-icon="&#57801;">Open/Close Menu</a>
          <div class="logo-wrapper">
            <a href="#" title="Seyha &amp; Linna" class="logo ">
              <img src="assets/wp-content/uploads/2013/10/Logo.png" alt="Nick &amp; Sarah" class="hide-hidpi" />
              <img src="assets/wp-content/uploads/2013/10/Logo@2x.png" alt="Nick &amp; Sarah" class="show-hidpi-inline" height="112" />
            </a>
            <div class="clearboth"></div>
            <a href="/" title="Nick &amp; Sarah" class="combined-logo-title">
              <div class="site-title-part left-name">Seyha</div>
              <div class="site-title-part name-delimiter">&amp;</div>
              <div class="site-title-part right-name">Linna</div>
            </a>
            <span class="logo-tagline">ARE GETTING MARRIED!</span>
          </div>
        </div>
        <div class="second-row">
          <div class="limit-wrapper">
            <div class="second-row-columns">
              <div class="header-center">
              </div>
            </div>
          </div>
        </div>
      </header>
      <img src="assets/wp-content/themes/the-wedding-day/wpv_theme/assets/images/svg/menu-lines.svg" onerror="this.onerror=null; this.src='https://the-wedding-day.vamtam.com/assets/wp-content/themes/the-wedding-day/wpv_theme/assets/images/menu-lines.png'"
        class="menu-lines" />
    </div>
    <div class="shadow-bottom"></div>
    <div class="boxed-layout">
      <div class="page-dash-wrapper">
        <div class="pane-wrapper clearfix">
          <header id="header-middle" class="row normal type-featured" style="background-color:#ffffff;min-height:0px">
            <div class="limit-wrapper">
              <div class="header-middle-content">
              </div>
            </div>
          </header>
          <div id="main-content">

            <div id="main" role="main" class="layout-full">
              <div class="limit-wrapper">
                <div class="pane main-pane">
                  <div class="row">
                    <div class="page-outer-wrapper">
                      <div class="clearfix page-wrapper">
                        <article id="post-4" class="full post-4 page type-page status-publish hentry">
                          <div class="page-content no-image">
                            <div class="push" style='height:20px'></div>
                            <h1 style="text-align: center;">Wedding Invitation</h1>
                            <div class="push" style='height:20px'></div>
                            <img class="aligncenter" style="position: relative; z-index: 99; bottom: -18px; left: -10px;" title="" src="assets/wp-content/uploads/2013/03/element-5.svg"
                              alt="" />
                            </p>
                            <div class="push" style='margin-bottom:-10px'></div>
                            <div class="row ">
                              <div class="wpv-grid grid-1-5  wpv-first-level first unextended" style="padding-top:0px;padding-bottom:0px"
                                id="wpv-column-a2206aded3ddee2c12400a3059dbbba8">
                                <div class="push" style='height:80px'></div>
                                <%= image_tag "portrait-man1.svg", class: "aligncenter size-full wp-image-6724", size: "165" %>
                                </p>
                                <h3 style="text-align: center;">Heng Seyha</h3>
                                <p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adi pisi cing elit, sed do eiusmod tempor exercitationemut
                                  labore et dolore magna aliqua. Ut enim ad consequatur quis nostrud exercitation ullamco
                                  laboris nisi ut aliquip ex ea commodo consequat&#8230;</p>
                                <p style="text-align: center;">
                                  <a href="https://www.facebook.com/sino.chef7">
                                    <span class='icon shortcode  ' style='font-size:26px !important;'>&#58157;</span>
                                  </a>
                                </p>
                              </div>
                              <div class="wpv-grid grid-3-5  wpv-first-level unextended" style="padding-top:0px;padding-bottom:0px" >

                                <div id="layerslider_1" class="ls-wp-container fitvidsignore" style="margin:0 auto;margin-bottom: 0px;">
                                  <div class="ls-slide1" data-ls="duration:4000;transition2d:5;kenburnsscale:1.2;">
                                    <%= image_tag "profile1.png", class: "ls-l", style: "border-radius: 1000px;top:0px;left:20px;", size: '800' %>
                                  </div>
                                </div>
                                <div class="push" style='height:3px'></div>
                              </div>
                              <div class="wpv-grid grid-1-5  wpv-first-level unextended" style="padding-top:0px;padding-bottom:0px" id="wpv-column-74d59e477a3b247776912d3411fd10bc">
                                <div class="push" style='height:80px'></div>
                                <%= image_tag "portrait-woman1.svg", class: "aligncenter size-full wp-image-6724", size: "165" %>
                                </p>
                                <h3 style="text-align: center;">Chhoeun Linna</h3>
                                <p style="text-align: center;">Sed auctor neque eu tellus rhoncus ut eleifend nibh porttitor. Ut in nulla enim. Phasellus
                                  molestie magna non est bibendum non venenatis nisl tempor. Suspendisse dictum me.</p>
                                <p style="text-align: center;">
                                  <a href="https://www.facebook.com/patchpatch.nona">
                                    <span class='icon shortcode  ' style='font-size:26px !important;'>&#58157;</span>
                                  </a>
                                </p>
                              </div>
                            </div>
                            <div class="row ">
                              <h1 style="text-align: center;">SATURDAY &#8211; 23 DECEMBER 2017<br>AT 4:00 O'CLOCK AT THE EVENING</h1>
                              <center><%= image_tag 'line.png', size: '550x250', style: 'margin-top:60px;' %></center>
                              <center><p style="font-size: 1.6em;">វេលាម៉ោង 4:00 រសៀលនៅគេហដ្ឋានខាងស្រី ភូមិក្បាលស្ពាន ឃុំម៉ាឡៃ ស្រុកម៉ាឡៃ ខេត្តបន្ទាយមានជ័យ</p></center>
                              <div class="wpv-grid grid-1-3  wpv-first-level first unextended" style="padding-top:0px;padding-bottom:0px"
                                id="wpv-column-b3c1d760f051b4c511323e89f6a6a50f">
                                <div class="push" style='height:10px'></div>
                              </div>
                            </div>
                            <div class="row ">
                              <div class="wpv-grid grid-1-1  wpv-first-level first unextended animation-fade-in animated-active"
                                style="padding-top:0px;padding-bottom:0px" id="wpv-column-30e760b17da7fc5967777b7b33b54e4e">
                                <div class="sep-3"></div>
                                <div class="push" style='height:5px'></div>
                                <h3 style="text-align: center;">Thank you for joining our special day with us</h3>
                                <h5 style="text-align: center;">~ we are sorry if something wrong in the party ~</h5>
                                <div class="push" style='height:40px'></div>
                              </div>
                            </div>
                            <div class="row ">
                              <div class="wpv-grid grid-1-1  wpv-first-level first has-background extended animation-fade-in animated-active"
                                style="
                                    background: url(<%= asset_path 'bor.png' %>) repeat-y center bottom;
                                    background-size: auto;
                                    background-attachment: scroll;
                                  background-color:#688a72;padding-top:15px;padding-bottom:35px" id="wpv-column-2573d5b8871ad2f811cd9ceeda5e6d62">
                                <div class="extended-column-inner">
                                  <div class="sep-text single centered">
                                    <span class="sep-text-before">
                                      <div class="sep-text-line"></div>
                                    </span>
                                    <div class="content">
                                      <h2>Just</h2>
                                    </div>
                                    <span class="sep-text-after">
                                      <div class="sep-text-line"></div>
                                    </span>
                                  </div>
                                  <div class="push" style='height:50px'></div>
                                    <center><div class="demo1 dsCountDown ds-white"></div></center>
                                  <div class="push" style='height:50px'></div>
                                  <h2 style="text-align: center;"> until we get parties!</h2>
                                </div>
                              </div>
                            </div>
                          </div>
                        </article>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="copyrights">
            <div class="limit-wrapper">
              <div class="row">
                <div class="push" style='height:20px'></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div id="scroll-to-top" class="icon">&#58006;</div>

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-dismissible alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{'aria-hidden' => 'true', 'data-dismiss' => 'alert', :type => 'button'} &times;
      = content_tag :div, msg, :id => 'flash_#{name}'

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{'aria-expanded' => 'false', 'data-target' => '#bs-example-navbar-collapse-1', 'data-toggle' => 'collapse', :type => 'button'}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => '#'} Brand
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li.active
          %a{:href => '#'}
            Link
            %span.sr-only (current)
        %li
          %a{:href => '#'} Link
      %ul.nav.navbar-nav.navbar-right
        %li.dropdown
          %a.dropdown-toggle{'aria-expanded' => 'false', 'aria-haspopup' => 'true', 'data-toggle' => 'dropdown', :href => '#', :role => 'button'}
            Dropdown
            %span.caret
          %ul.dropdown-menu
            %li
              %a{:href => '#'} Action
            %li
              %a{:href => '#'} Another action
            %li
              %a{:href => '#'} Something else here
            %li.divider{:role => 'separator'}
            %li
              %a{:href => '#'} Separated link

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Invitation
    = csrf_meta_tags
    = stylesheet_link_tag    'application'
    = javascript_include_tag 'application'
    :css
      img.wp-smiley,
      img.emoji {
        display: inline !important;
        border: none !important;
        box-shadow: none !important;
        height: 1em !important;
        width: 1em !important;
        margin: 0 .07em !important;
        vertical-align: -0.1em !important;
        background: none !important;
        padding: 0 !important;
      }
    :javascript
      jQuery(document).ready(function($){
        $('.demo1').dsCountDown({
          endDate: new Date("December 23, 2017 17:59:00")
        });
      });
    %link#ls-google-fonts-css{:href => "https://fonts.googleapis.com/css?family=Lato:100,300,regular,700,900%7COpen+Sans:300%7CIndie+Flower:regular%7COswald:300,regular,700&subset=latin%2Clatin-ext", :media => "all", :rel => "stylesheet", :type => "text/css"}/
    %link#wpv-gfonts-css{:href => "https://fonts.googleapis.com/css?family=Cinzel%3Anormal%7CClicker+Script%3Anormal%2C300%7CDroid+Sans%3Anormal%7CCinzel+Decorative%3Anormal&subset=cyrillic%2Cgreek%2Clatin&ver=18", :media => "all", :rel => "stylesheet", :type => "text/css"}/
    %style#front-all-inline-css{:type => "text/css"}
      :cdata
        @media (min-width: 1300px) {
        body.full header.main-header .first-row { background-size: 101% auto; }
        }
        .page-id-6172 header.main-header .first-row,
        body.page-id-6172 {
        background: #fff;
        }
        body.page-id-6172 .copyrights { display: none }
    :css
      .recentcomments a{display:inline !important;padding:0 !important;margin:0 !important;}
  %body{ id: '#{controller_name}_#{params[:action]}' }
    = yield